### ISSUE TITLE
Homey.notifications.getNotifications(); returns You have no access to do this.

### ISSUE THREAD

**Issue by Dijker** [athombv/web-api-issues#1]
Don't know if this is an HomeyScript Issue or an WebAPI Issue

Homey 2.0.0-rc.8
HomeyScript v1.1.0 

// my script
let notifications = await Homey.notifications.getNotifications();
log(notifications)

----------------
Script Error:
You have no access to do this.

**Comment by WeeJeWel** [comment]
Apps have no access to a user's notifications due to protection of said user's privacy.
