### ISSUE TITLE
ManagerDevices.getDevice not updating capabilitiesObj in real time

### ISSUE THREAD

**Issue by gruijter** [athombv/web-api-issues#12]
athom api: 2.1.220
homey fw: 3.1.0

```const device = await this.api.devices.getDevice(id);```

results in a device instance of which the capabilitiesObj is not updated on every change in capability. It seems to be updated only a few times per hour. This means the capability values do not reflect the actual values of the device.

**Comment by WeeJeWel** [comment]
You should use Device.makeCapabilityInstance to get the latest values of `value` and `lastChanged`.
