### ISSUE TITLE
device.capabilitiesObj returns null while device is ready.

### ISSUE THREAD

**Issue by daneedk** [athombv/web-api-issues#16]
Since the release of Homey firmware v7.4.1, the Heimdall app is regularly crashing because of this error:

`TypeError: Cannot use 'in' operator to search for 'alarm_motion' in null
at Heimdall.checkDeviceState (/app.js:831:29)
    at Heimdall.checkDevicesState (/app.js:818:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

This is the relevant code:
<img width="767" alt="image-7" src="https://user-images.githubusercontent.com/16610696/169653733-b2aaafe3-eb46-4aa0-bb06-1ddfd26f391c.png">

As you can see on line 826 there is a check if the device is ready. I would assumed the `device.capabilitiesObj` would return `{}` and not `null`. 
I've reported this on Slack, Jeroen Wink asked me to report it here.

For now I've 'fixed' this by replacing line 826 with line 827:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/16610696/169654068-4a3562eb-b677-41f6-8d65-1a3db5bba4d4.png">

(btw. there is an older issue opened bij Robert Klep that may be related: https://github.com/athombv/homey-web-api-issues/issues/3)

**Comment by WeeJeWel** [comment]
Device Update events may come in separately so the correct way is to always check if `capabilitiesObj` actually is an object, e.g. `device.capabilitiesObj?.onoff`.
