### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Erik-Lam** [athombv/web-api-issues#2]
The [documentation of ManagerPresence](https://developer.athom.com/docs/api/HomeyAPI.ManagerPresence.html) shows wrong function names.
E.g. getPresent() should be getPresence().
<img width="395" alt="image" src="https://user-images.githubusercontent.com/33542970/50441480-2ad61f00-08fb-11e9-881d-d2228c229927.png">

**Comment by WeeJeWel** [comment]
This is correct. getPresent returns a value `present` which is either `true` or `false`.
