### ISSUE TITLE
Issue with calling `makeCapabilityInstance()` multiple times for the same device/capability.

### ISSUE THREAD

**Issue by robertklep** [athombv/web-api-issues#22]
Background: my HomeKitty app allows devices to be (un-)exposed from HomeKit. When a device is unexposed, I will stop listening to capability changes by destroying a previously created capability instance (using `device.makeCapabilityInstance()`).

However, when a device is exposed to HomeKit again, it should start listening to capability changes and I create a new capability instance for that. But the listener for that instance is never called when the capability changes.

Code to reproduce (replace the device id with one of your own devices that has an `onoff` capability):
```
const Homey = require('homey');
const { HomeyAPIApp } = require('homey-api');

module.exports = class MyApp extends Homey.App {

  async onInit() {
    const api = new HomeyAPIApp({ homey: this.homey });
    await api.devices.connect();
    const device = await api.devices.getDevice({ id : 'ccafde03-6c28-44b8-8ace-78d867c19f48' });
    this.makeCapabilityInstance(device);
  }

  makeCapabilityInstance(device) {
    this.log('making capability instance');
    const instance = device.makeCapabilityInstance('onoff', value => {
      this.log(`device ${ device.name } onoff changed to "${ value }"`);
      this.log(`destroying instance`);
      instance.destroy();
      setTimeout(() => {
        this.makeCapabilityInstance(device);
      }, 2000);
    });
  }
}
```

This logs:
```
[log] 2023-01-10 13:18:34 [MyApp] making capability instance
[log] 2023-01-10 13:18:37 [MyApp] device HK Light onoff changed to "true"
[log] 2023-01-10 13:18:37 [MyApp] destroying instance
[log] 2023-01-10 13:18:39 [MyApp] making capability instance
```

So the first change of `onoff` calls the listener, then destroys it, then waits 2s (to rule out a timing issue) and creates a new one, but the second listener is never called when I change the capability from the web app.

**Comment by robertklep** [comment]
If I'm reading the code correctly, it might be caused by the connect/disconnect logic in `Item.js`:
* in `Item#connect()`, if `this.io` doesn't exist, a new realtime subscription is created
* in `Item#disconnect()`, the subscription is unsubscribed (`io.unsubscribe()`) _but `this.io` remains defined_
* then in a new call to `Item#connect()`, `this.io` already exists and no new subscription is created.

**Comment by robertklep** [comment]
A workaround would be to retrieve a new uncached device instance every time:
```
setTimeout(() => {
  this.makeCapabilityInstance(await this.api.devices.getDevice({ id : 'ccafde03-6c28-44b8-8ace-78d867c19f48', $cache : false }));
}, 2000);
```
But that seems like a waste of resources.

**Comment by robertklep** [comment]
Better workaround: when cleaning up the old listeners, I set `device.io = null`, which confirms my suspicion from [my comment](https://github.com/athombv/homey-web-api-issues/issues/22#issuecomment-1377307733) about the realtime subscription handling.

**Comment by jeroenwienk** [comment]
Fixed in https://www.npmjs.com/package/homey-api/v/1.10.8

**Comment by OlivierZal** [comment]
I confirm this is fixed.

Thanks @jeroenwienk
