### ISSUE TITLE
`setValue` cannot apply to `CapabilityInstances`

### ISSUE THREAD

**Issue by OlivierZal** [athombv/web-api-issues#23]
[Web API documentation says](https://athombv.github.io/node-homey-api/HomeyAPIV2.ManagerDevices.Device.html#makeCapabilityInstance) that a `CapabilityInstance` is to switch `on` this way:
```
capabilityInstance.setValue(true).catch(this.error)
```

but errors are raised:
```
[err] 2023-01-19 23:45:54 [MELCloudApp] [HomeyAPIError: Une erreur inconnue s'est produite [not_setable]] {
  statusCode: 500,
  description: "Une erreur inconnue s'est produite [not_setable]"
}
```
or
```
[err] 2023-01-19 23:46:30 [MELCloudApp] [HomeyAPIError: not_setable] {
  statusCode: undefined,
  description: null
}
```

**Comment by jeroenwienk** [comment]
This is not a bug but you are trying to set a capability that is not setable.The error code is wrong though.

**Comment by OlivierZal** [comment]
Understood @jeroenwienk
