### ISSUE TITLE
[TypeScript] `HomeyAPIxxx.ManagerDevices.Device.setCapabilityValue` signature error

### ISSUE THREAD

**Issue by OlivierZal** [athombv/web-api-issues#28]
```
setCapabilityValue(
  opts: {
    capabilityId: string,
    value: number | boolean | string,
    opts: {
      duration: number,
    },
)
```

should rather be:

```
setCapabilityValue(
  opts: {
    capabilityId: string,
    value: number | boolean | string,
    // The part below is not necessary to make the function work
    opts?: {
      duration?: number,
    },
)
```

**Comment by jeroenwienk** [comment]
This one seems correct. You should always use the type of V3.

**Comment by OlivierZal** [comment]
The problem is the first `opts` in the type.

**Comment by OlivierZal** [comment]
The problem has changed: the opts seems mandatory.

**Comment by OlivierZal** [comment]
The opts is mandatory (opts should be optional) and the duration in opts too

**Comment by OlivierZal** [comment]
@jeroenwienk, my bad the issue has been wrongly specified, now the problem is the mandatory opts (in opts). 

Should rather be:

```
setCapabilityValue(
  opts: {
    capabilityId: string,
    value: number | boolean | string,
    opts?: {
      duration?: number,
    }
  }
)
```

**Comment by OlivierZal** [comment]
@jeroenwienk, my bad, I wrote the wrong way.

My point is that the function works well without the (second) `opts`, what means that it needs to be marked as optional in the definition:

```
opts?: {
  duration?: number,
}
```

I've updated the description accordingly with the following:

```
setCapabilityValue(
  opts: {
    capabilityId: string,
    value: number | boolean | string,
    opts?: {
      duration?: number,
    }
  }
)
```

**Comment by jeroenwienk** [comment]
It is marked as optional in the types.

**Comment by OlivierZal** [comment]
I’ll screenshot the error when I’m home…

**Comment by OlivierZal** [comment]
I don't know when it has been solved but now it's good. Thanks!
