### ISSUE TITLE
Listen to non-capability events (aka button presses)

### ISSUE THREAD

**Issue by crashkonijn** [athombv/web-api-issues#31]
Hi!

Let me start by saying I have been using Homey for a couple years and I've been loving it so far!

However one thing I've always hated doing is implementing all features for buttons. With the ikea bridge (for example) it's much easer to just connect a button to a (group?) of lights and the expected features just work. Implementing all 10 buttons I have manually per event was hell (although I do imagine it get's easier with advanced flows).

Later this year I'm moving to a new home and I'm not looking forward to setting it up again. I'm currently working on a couple apps that will handle a couple things within homey that take to much effort, but as far as I'm aware I'm unable to implement a fix for my issue with buttons.

What I'd like to suggest is the following:

> Make it possible to register to card triggers that are not created by your own app. Perhaps comparable to how you can register to changes on devices by using `device.makeCapabilityInstance`?

As far as I can tell #19 was looking for the same thing.

One other possibility I could think of is to generate flows using code to bind certain events to my app, but as far as I'm aware an app is not allowed to do this, even with the `homey:manager:api` permission.

Thanks for reading!

**Comment by b03tz** [comment]
+1 sounds good!

**Comment by WeeJeWel** [comment]
Our philosophy is that the user is always in control of their automations, so they should create a Flow themselves to link two apps together. So currently this is not something we're planning to support.

**Comment by crashkonijn** [comment]
Hi!

I don't think this feature would not align with your philosophy. In essence is the feature that's missing exactly the same as the `< groep >` app.

Right now it's possible to register to any change of any device registered to your Homey, then do something based on that (which is what `< groep >` does).

I would like to be able to listen to events, like `press_up` on a button such that it would be possible to make a card like `When press_up in room`.
