### ISSUE TITLE
this.homeyAPI.insights.getLogEntries(opts) on HP2019 doesn't respect resolution

### ISSUE THREAD

**Issue by XeroxQ** [athombv/web-api-issues#32]
On the HP2019 at least, this doesn't go correctly:
i request this:
{
  uri: "homey:log:homey:device:2d209601-4ebc-467d-8225-7f3439441f19:energy_power",
  id: "homey:device:2d209601-4ebc-467d-8225-7f3439441f19:energy_power",
  $timeout: 90000,
  resolution: "lastHour",
}
And i get back:
{
  values: [
    {
      t: "2023-05-14T22:00:00.000Z",
      v: 0.5,
    },
.........
      t: "2023-05-15T18:25:00.000Z",
      v: null,
    },
  ],
  start: "2023-05-14T22:00:00.000Z",
  end: "2023-05-15T18:30:00.000Z",
  step: 300000,
  uri: "homey:device:2d209601-4ebc-467d-8225-7f3439441f19",
  id: "energy_power",
  lastValue: 6,
  updatesIn: 124541,
}
On the HP2023, this does go correctly.

**Comment by spkesDE** [comment]
Can confirm! :)

https://athomcommunity.slack.com/archives/C04LQVDTY5S/p1685288250753929
https://community.homey.app/t/app-pro-insight-trends-reloaded/71307/246?u=spkesde

**Comment by jeroenwienk** [comment]
Fixed in latest version.

**Comment by jozahner** [comment]
Which version is „latest“?

**Comment by spkesDE** [comment]
3.0.5 currently
