### ISSUE TITLE
[TypeScript] `homey-api.d.ts` is broken on 3.0.5

### ISSUE THREAD

**Issue by OlivierZal** [athombv/web-api-issues#34]
TypeScript compilation fails because of this:

<img width="813" alt="Capture d’écran 2023-07-06 à 23 49 49" src="https://github.com/athombv/homey-web-api-issues/assets/88216225/580648ed-86bb-4b08-b1eb-0f28e70d02b5">

**Comment by spkesDE** [comment]
Same for me.

**Comment by jeroenwienk** [comment]
Could you guys lets me know if it's fixed in 3.0.6?

**Comment by jeroenwienk** [comment]
I also noticed the api does not have any manager types on homey.somemanager. How did you guys work around this? Seems that alot of stuff is not working propertly for ts.

**Comment by spkesDE** [comment]
With //ts-ignore 😅

Will test 3.0.6 later, once I‘m home

**Comment by OlivierZal** [comment]
I will test when I am home. 

For now I `ts-expect-error`

**Comment by OlivierZal** [comment]
And I think that some quick wins could be done for signature errors

For examples: https://github.com/athombv/homey-web-api-issues/issues/33

**Comment by OlivierZal** [comment]
Or https://github.com/athombv/homey-web-api-issues/issues/28 and https://github.com/athombv/homey-web-api-issues/issues/27

And a last one:

Current definition: new HomeyAPIApp(this.homey, false);

Right definition: new HomeyAPIApp({ homey: this.homey, debug?: false })

**Comment by jeroenwienk** [comment]
I will see if I can address those first

**Comment by OlivierZal** [comment]
Thanks a lot!

I say these are quick wins because @spkesDE and I give you the way to solve. 😀

**Comment by OlivierZal** [comment]
@jeroenwienk, many thanks 3.0.7 solves the issue and works perfect!

A version 3.0.8 with the following would be even more perfect 😀 

```
setCapabilityValue(
  opts: {
    capabilityId: string,
    value: number | boolean | string,
    opts?: {
      duration?: number,
    }
  }
)
```

By the way, how does `duration` work, I haven’t seen it documented somewhere…

**Comment by jeroenwienk** [comment]
> setCapabilityValue

Not sure what you mean that is the signature currently?

**Comment by OlivierZal** [comment]
Currently it's:

```
setCapabilityValue(
  opts: {
    capabilityId: string,
    value: number | boolean | string,
    opts: {
      duration: number,
    }
  }
)
```

where `opts: { duration: number }` is mandatory

Since `opts` is optional (the code works without it...), there is a missing `?`

**Comment by OlivierZal** [comment]
Note: I'm speaking about the "second" `opts`...

**Comment by OlivierZal** [comment]
Actually it’s more than I guess, because the code works without opts, so the issue comes from type definitions.

**Comment by OlivierZal** [comment]
Anyway, this issue is solved, I will create different tasks for the pending issues.
Thanks!
