### ISSUE TITLE
athom-api 2.1.147  cant access folders on Homey 1.5.x

### ISSUE THREAD

**Issue by Dijker** [athombv/web-api-issues#4]
Is it possible to use athom-api 2.1.147 in one Web-App to communicate to both v1.5 and v2.0 Homeys?

using api 2.0 with Homey 1.5 a HomeyAPI.flow.getFolders() works
using api 2.1 connecting Homey 2.0 it is HomeyAPI.flow.getFlowFolders() ....  
but connecting back to a 1.5 Homey  It responds with GET http://10.1.13.114/api/manager/flow/flowfolder with a 404 (Not Found) :disappointed: 
and .flow.getFolders()  is not a function...

I read there where some things back-ported to make them compatible?

**Comment by WeeJeWel** [comment]
No, the api client will not be backported to support v1.5.
