### ISSUE TITLE
WebApi v3 - createAppAPI - missing scope "homey.app.control"

### ISSUE THREAD

**Issue by martijnpoppen** [athombv/web-api-issues#45]
When calling `apps.getAppSetting({ name: 'variables', id: 'net.i-dev.betterlogic'})` it returns a missing scopes.
This was working with WebAPi V2

This only happens on HP23.

HP19 works fine

**Comment by jeroenwienk** [comment]
> When calling `apps.getAppSetting({ name: 'variables', id: 'net.i-dev.betterlogic'})` it returns a missing scopes. This was working with WebAPi V2
> 
> This only happens on HP23.
> 
> HP19 works fine

Seems it's missing yes will see if I can add it.

**Comment by martijnpoppen** [comment]
Thank you :)
