### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by markusv** [athombv/web-api-issues#48]
Where can I find the changelog for the [homey-api](https://www.npmjs.com/package/homey-api) npm package? It is not on npm and not in this repo. Where can we find it. What is for example new in versiono 3.x of the package?

**Comment by jeroenwienk** [comment]
> Where can I find the changelog for the [homey-api](https://www.npmjs.com/package/homey-api) npm package? It is not on npm and not in this repo. Where can we find it. What is for example new in versiono 3.x of the package?

I am sorry but we are currently not able to provide a changelog. Will see if we can change that in the future.

**Comment by markusv** [comment]
I am a little bit confused here. How are we supposed to use this API if we do not get any information on the changes as you develop it?

**Comment by jeroenwienk** [comment]
> I am a little bit confused here. How are we supposed to use this API if we do not get any information on the changes as you develop it?

You are right it's just that some of there changes right now are quite internal and not really relevant to anyone else using homey-api.

**Comment by markusv** [comment]
Still confues. Will you publish changelogs later on? Can you at least say what is new in the major versions? What has changed from version 1 to 3 for example. Any API changes? 

When I tried 3.0.4 I think it was I got a lot of errors with variables.

**Comment by WeeJeWel** [comment]
Currently there is no public changelog.

If a major version breaks, we document it on the Developer Documentation.
