### ISSUE TITLE
Homey.devices.getDevices - always invalid data node

### ISSUE THREAD

**Issue by hive** [athombv/web-api-issues#5]
When using the Homey.devices.getDevices({ online: true }), from the example, the data attribute is always 'undefined'. 

This can be seen with in the examples response. 

Note that as the SDK driver -> getDevice requires the data field, it means that there is no way to relate web/sdk devices from with in an app. 

![image](https://user-images.githubusercontent.com/239140/50732217-6f4e9e00-11ca-11e9-9129-5be8e2fcb9d1.png)

![image](https://user-images.githubusercontent.com/239140/50732209-34e50100-11ca-11e9-9ab6-4d190bcc6946.png)

**Comment by WeeJeWel** [comment]
Fixed in v2.0.0-rc.13
