### ISSUE TITLE
homey.device.on('capability.update') is broken and never fires

### ISSUE THREAD

**Issue by hive** [athombv/web-api-issues#51]
Currently the capability update/create/delete events documented  here : https://athombv.github.io/node-homey-api/HomeyAPIV3Local.ManagerDevices.html#.event:%22capability.update%22 will never fire.

And thus its not possible to listen to capability changes and provide appropriate updates.

I would expect that this event emitter (specifically the update) provide similar information to the makeCapabilityInstance at the same time.

**Comment by jeroenwienk** [comment]
> Currently the capability update/create/delete events documented here : https://athombv.github.io/node-homey-api/HomeyAPIV3Local.ManagerDevices.html#.event:%22capability.update%22 will never fire.
> 
> And thus its not possible to listen to capability changes and provide appropriate updates.
> 
> I would expect that this event emitter (specifically the update) provide similar information to the makeCapabilityInstance at the same time.

This event is not the same as the one from a capability instance.

**Comment by hive** [comment]
Is it for when a capability is added or removed from a device? When would you expect the update to fire?

**Comment by WeeJeWel** [comment]
`capability.update` probably won't fire, because (custom) Capabilities are only created and deleted.

**Comment by jeroenwienk** [comment]
> Is it for when a capability is added or removed from a device? When would you expect the update to fire?

A capability is an item in the backend of Homey. These events are when capabilities are created for apps,system.

To listen to capability changes of a device a [capability instance](https://athombv.github.io/node-homey-api/HomeyAPIV2.ManagerDevices.Device.html#makeCapabilityInstance) can be created. Or to listen to all changes on a device the `device.on('capability', (value) => {})` can be used. Note that this wont update the values inside the `device.capabilitiesObj `automatically so it is advised to use the capability instance method.
