### ISSUE TITLE
429 (Too Many Requests)

### ISSUE THREAD

**Issue by markusv** [athombv/web-api-issues#52]
I am getting a 429 Too many requests response to `https://api.athom.com/user/me`. What is the actual rate limit here? How many requests are we allowed to make?

This is on the newest version of the homey api: 3.4.19. Strangely the homey web app on the same device does still work though

This is my code:

```typescript

const loggedIn = await cloudApi.isLoggedIn();
if (!loggedIn) {
  if (cloudApi.hasAuthorizationCode()) {
    const token = await  cloudApi.authenticateWithAuthorizationCode();
  } else {
    window.location.href =  cloudApi.getLoginUrl();
    return;
  }
}
const user = await cloudApi.getAuthenticatedUser();
const homey = await user.getFirstHomey();
const homeyApi = await homey.authenticate();
```

<img width="520" alt="Skjermbilde 2024-01-28 kl  19 23 11" src="https://github.com/athombv/homey-web-api-issues/assets/475663/50a15d13-dd22-4d0a-807f-1a42f4e046ec">

**Comment by jeroenwienk** [comment]
> I am getting a 429 Too many requests response to `https://api.athom.com/user/me`. What is the actual rate limit here? How many requests are we allowed to make?
> 
> This is on the newest version of the homey api: 3.4.19. Strangely the homey web app on the same device does still work though
> 
> This is my code:
> 
> ```ts
> const loggedIn = await cloudApi.isLoggedIn();
> if (!loggedIn) {
>   if (cloudApi.hasAuthorizationCode()) {
>     const token = await  cloudApi.authenticateWithAuthorizationCode();
>   } else {
>     window.location.href =  cloudApi.getLoginUrl();
>     return;
>   }
> }
> const user = await cloudApi.getAuthenticatedUser();
> const homey = await user.getFirstHomey();
> const homeyApi = await homey.authenticate();
> ```
> 
> <img alt="Skjermbilde 2024-01-28 kl 19 23 11" width="520" src="https://private-user-images.githubusercontent.com/475663/300284892-50a15d13-dd22-4d0a-807f-1a42f4e046ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTk5MDgsIm5iZiI6MTcxMjU1OTYwOCwicGF0aCI6Ii80NzU2NjMvMzAwMjg0ODkyLTUwYTE1ZDEzLWRkMjItNGQwYS04MDdmLTFhNDJmNGUwNDZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwNzAwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDFmNzI2YmNlNDY4ZDJlODhkYmI0MWYyZTQ0M2NkOTAxM2Y3ZTZiMWVlOWYwNGRiMjhlNDQ4NTY0YjhkNDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rhVoe2-aYYv7ITm3oyW_OKrzKKEJc9Jpzz_3UQznuZQ">

Rate limits are also based on a cloud-api client id. We are not going to communicate the current limits for this since they might change.

**Comment by markusv** [comment]
Thanks for the response. I am now using one of the new api keys. No rate limit with that it seems, so my problem is solved
