### ISSUE TITLE
Error : 408, Timeout after 5000ms : weather endpoint

### ISSUE THREAD

**Issue by hive** [athombv/web-api-issues#54]
I am receiving a 408 error from the weather endpoint, **however** this in fact seems to be a rate limit. 

I am calling the endpoints `getWeather` once a minute, after a while I start getting the 408 error until I stop.

Further to this, my app also seems to be breaking the homey iOS app, the home page (which ahs the weather on it) will throw a rate_limited exception page. 

Once a minute hardly seems excessive, given it updates every 15 minutes. 

What is the rate limit for the weather endpoint, and can it please be documented.

**Comment by hmeerlo** [comment]
the ratelimit for getWeather is 20 times per minute, 100 calls per hour and max 300 calls per day.

**Comment by hive** [comment]
Thank you for the quick answer, this same api and rate limit is used also for the app.

How many calls is that making? If I call once every 5 minutes will the iOS app continue to give a rate limit error? 

Is there any chance that rather then poking we could get an event on change?

**Comment by PeterKawa** [comment]
The weather gets updated while nothing  changed. That's weird, a waste and useless.

How can we make sure the weather only sends changes instead of updates with just the same values?
Also, is it possible to only send the changed value(s), instead of just all values?
