### ISSUE TITLE
HomeyAPI.ManagerDevices.Device.CapabilityInstance setValue() triggers listeners function

### ISSUE THREAD

**Issue by specialcircumstances** [athombv/web-api-issues#6]
SDKv2. Latest stable Homey.

Documentation indicates:

listener | function | A function to invoke when the capability is changed by anything other than the returned capabilityInstance

When I use the setValue() method of the returned capabilityInstance the listener function is triggered.

Creation of instance:
```
device['cInst']['target_temperature'] = device.makeCapabilityInstance('target_temperature', function(device) {
                this.stateChange(device);
            }.bind(this, device));
```

Trigger of method:

`await thisDevice.cInst.target_temperature.setValue(targetTemp);
`

Result is that "stateChange(device)" is triggered.

**Comment by WeeJeWel** [comment]
Well, yes, the value is changed!

**Comment by specialcircumstances** [comment]
Lol... that was a long time ago... I think the point I was querying was that the documentation indicates " when the capability is changed by **anything other than the returned capabilityInstance** "
It was so long ago I can't really remember the details...

**Comment by WeeJeWel** [comment]
Aha, thanks, we'll add that in a future release :)
