### ISSUE TITLE
Unable to call Homey.rf.emulate from HomeyScript: You have no access to do this

### ISSUE THREAD

**Issue by sherland** [athombv/web-api-issues#8]
I'm trying to send ir-commands by using [HomeyScript](https://apps.athom.com/app/com.athom.homeyscript)
When I run this script in the [HomeyScript console](https://homeyscript.homey.app/):

``` javascript
let data = [545,1696,535 /* dummy-data */] 
await Homey.rf.emulate({frequency: 'ir', data: data});
```

... I get this error:

```
----------------
Script Error:
You have no access to do this.
```

One strange(?) thing is that if I run this in the [api-playgound](https://developer.athom.com/tools/api-playground), I don't get any errors, or 'ok' for that matter... (I had to remove 'await' for some reason):
``` javascript
let data = [545,1696,535 /* dummy-data */] 
Homey.rf.emulate({frequency: 'ir', data: data});
```

**Comment by jeroenvollenbrock** [comment]
Homey.rf.emulate does not send ir commands, instead it pretends it just received the specified raw data. This is a developer API meant for the creation of new apps and signals, and is therefore not available within homeyscript.
